version: "3"

services:
  buddi:
    environment:
      - DATABASE_URL=ecto://postgres:postgres@localhost:5432/buddi_manager_dev
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:3000"
    depends_on:
      - db

  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/PGDATA
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
